NascentCore/3k

examples/bert_deepspeed/k8s_config/mpi_bert_dp.yaml

add mpi yaml

---

examples/bert_deepspeed/dockerfile
examples/bert_deepspeed/k8s_config/mpi_bert_ds.yaml
examples/bert_deepspeed/requirements.txt

update dockerfile yaml

---

examples/bert_deepspeed/train_bert_ds.py

测试完成删除fire

---

examples/bert_deepspeed/train_bert_ds.py

Mpi rank question

---

examples/bert_deepspeed/train_bert_ds.py

ad-hoc fix to the conflicting MPI env vars of OMPI_COMM_WORLD_LOCAL_RANK and LOCAL_RANK

---

operator/install_kubeflow.sh

Fix printed message of installing Kubeflow

---

examples/bert_deepspeed/train_bert_ds.py

添加args参数解析

---

examples/hf_model/README.md

Added hf_model dir

---

examples/bert_deepspeed/train_bert_ds.py

修正checkpoint重载的代码

---

k8s/ceph/README.md

Add ceph dir

---

examples/bert_deepspeed/train_bert_ds.py

完善checkpoint重载功能

---

examples/bert_deepspeed/model_roberta_base/README.md

Added README.md

---

examples/bert_deepspeed/README.md

Add the links to the original files

---

examples/bert_deepspeed/train_bert_ds.py

Load pretrained model `roberta-base` for training bert model

---

k8s/README.md

Add instruction of copying kubeconfig README.md

---

.gitignore
examples/bert_deepspeed/Dockerfile
examples/bert_deepspeed/hostfile
examples/bert_deepspeed/k8s_config/mpi_bert_ds.yaml
examples/bert_deepspeed/train_bert_ds.py
examples/cifar-10/training.yaml

Merge in recent changes to the configuration

---

examples/bert_deepspeed/trani_bert_ds_original.py

jim add bert original file for fix k8s erro

---

k8s/ceph/ceph-admin-secret.yaml

Fix typo kube-systemexit -> kube-system

---

operator/install_kubeflow.sh

Revise install kubeflow sh

---

cli/README.md

Add CLI dir

---

home/congpeiqing/README.md

add home/congpeiqing/README.md

Add congpeiqing

---

home/zhaoyan/README.md

my first pr

---

k8s/gpumon/README.md
k8s/gpumon/promethues-gpumonitor.yaml

添加promethues-gpumonitor.yaml
使Prometheus能够从DCGM- exporter中拉取数据

add promethues-gpumonitor.yaml

---

examples/nccl/0.build_and_push_docker_image.sh
examples/nccl/1.k8s_apply_yaml.sh
examples/nccl/Dockerfile
examples/nccl/base.Dockerfile
examples/nccl/entrypoint.sh
examples/nccl/k8s_nccl_test.yaml
examples/nccl/nccl_test_locally.py

new Dockerfile for nccl test

---

.github/scripts/check_tests.sh
.github/workflows/additional_lint.yaml

Add CI test that checks go test file exists

---

examples/bert/k8s_config/mpi_bert_ds.yaml
experimental/demo_test.go

This reverts commit ceb2fbaa5e30933dca8bc99dc3b538313ea0962e.

Revert "Update mpi_bert_ds.yaml"

---

home/README.md

Add README.md to home dir.

---

.github/workflows/additional_lint.yaml

Disable readme.md check

---

devops/ansible/README.md
devops/ansible/go.yaml

Add devops/ansible

---

manager/build/README.md
manager/build/cpodmanager.yaml
manager/cmd/cpodmanager/cpodmanager.go
manager/cmd/slicetest/slicetest.go
manager/pkg/cluster/client-go/client.go
manager/pkg/storage/s3.go

add serviceaccount and clusterrole for mpijob

add serviceaccount and clusterrole for mpijob

---

.github/scripts/check_all.sh
.github/scripts/check_go_tests.sh
.github/workflows/additional_lint.yaml
devops/ansible/python.yaml

Include all checks in check_all.sh

---

manager/cmd/cpodmanager/cpodmanager.go
manager/pkg/communication/marketmanager.go
manager/pkg/job/README.md
manager/pkg/job/job.go
manager/pkg/job/kubeflow-mpijob/mpijob.go
manager/pkg/job/kubeflow-mpijob/mpijob_status.go
manager/pkg/resource/resource.go
manager/pkg/resource/resource_test.go

complete resource related data defination

Resource data define

---

manager/cmd/cpodmanager/cpodmanager.go
manager/pkg/resource/resource.go

从API Server中获取节点信息，提取信息到Resource Info

get resource info from apiserver

---

home/cairong/README.md
home/cairong/bubble_sort.go
home/cairong/bubble_sort_test.go

cairong's first pr

---

.github/scripts/check_go_tests.sh

Exit with the right code

---

market-manager/pkg/utility/utility.go
pkg/utils/consts/consts.go
pkg/utils/consts/http.go

Add http consts

---

tools/super_linter.sh

Add check of number of arguments (now requires specifying targets)

---

examples/IB/README.md

add ibping in readme

---

manager/cmd/modeluploader/modeluploadjob.go
manager/pkg/model-uploader/README.md
manager/pkg/model-uploader/model_uploader.go

model upload job skeleton

---

examples/IB/sriov-ib-network-deployment.yaml
examples/IB/sriov-ib-network-node-policy.yaml
examples/IB/sriov-ib-network-pod.yaml
examples/IB/sriov-ib-network.yaml

add sriov-ib-network yaml

---

manager/cmd/modeluploader/modeluploadjob.go
manager/pkg/model-uploader/model_uploader.go
manager/pkg/model-uploader/model_uploader_test.go

model upload , add flag file

---

examples/IB/sriov-ib-network-deployment.yaml
examples/IB/sriov-ib-network-node-policy.yaml
examples/IB/sriov-ib-network-pod.yaml
examples/IB/sriov-ib-network.yaml

fix yaml-lint error

---

manager/pkg/communication/marketmanager.go
manager/pkg/communication/marketmanager_test.go
manager/pkg/resource/resource.go

add cpod level resource stat

---

tools/super_linter.sh

Use singapore image repo for accessing super-linter

---

examples/llama2/llama2_demo.py
examples/llama2/requirements.txt

Used `torch.distributed.launch` to kick off the single-node-multi-GPU training on a single node equipped with IB NICs.

used torch.distribute.launch to kick off the training

---

examples/bert/train_bert_ds.py

Add --datasets_dir to specify local dataset in train_bert_ds.py

---

devops/docker/cpodmanager/Dockerfile
devops/docker/cpodmanager/README.md

Create Dockerfile for building cpodmanager docker container image

---

manager/pkg/model-uploader/k8s_job.go

add model upload job json spec

---

examples/bert/k8s_config/mpi_bert_ds.yaml

Add newest working config on testing env for mpi_bert_ds.yaml

---

manager/cmd/modeluploader/modeluploadjob.go
manager/pkg/communication/marketmanager.go
manager/pkg/job/job.go
manager/pkg/job/kubeflow-mpijob/mpijob_state.go
manager/pkg/model-uploader/model_uploader.go
manager/pkg/storage/oss.go

model upload module

---

go.mod
go.sum
manager/cmd/cpodmanager/cpodmanager.go
manager/cmd/modeluploader/modeluploadjob.go
manager/pkg/communication/marketmanager.go
manager/pkg/job/job.go
manager/pkg/job/kubeflow-mpijob/mpijob.go
manager/pkg/job/kubeflow-mpijob/mpijob_state.go
manager/pkg/log/log.go
manager/pkg/model-uploader/model_uploader.go
manager/pkg/storage/oss.go

在关键位置添加日志
添加同步启动Model Upload Job的逻辑

mvp prepare

---

deployment/ceph/secret.yaml
examples/bert/Dockerfile
examples/bert/k8s_config/mpi_bert_ds.yaml

Tested on LY cluster:
```
k create ns bert 
k apply -f examples/bert/k8s_config/mpi_bert_ds.yaml -n bert
```

Complete example of mounting CephFS into MPIJob

---

examples/llama2/config/k8s/llama2-deepspeed-mpi.yaml

Use ly local configs

---

manager/build/cpodmanager.yaml
manager/cmd/modeluploader/Dockerfile
manager/cmd/modeluploader/README.md
manager/cmd/modeluploader/buildimage.sh
manager/cmd/modeluploader/modeluploadjob.go
manager/pkg/model-uploader/k8s_job.go

some modification for modeluploader: 
1 . get oss aksk from secret
2. Dockerfile and build scripts
3. rbac

modeluploader 

---

examples/bert/Dockerfile
examples/bert/k8s_config/mpi_bert_ds.yaml
examples/bert/restart.sh
examples/bert/train_bert_ds.py

Bert mpijob with additional config to write ckpt to mounted cephfs path

---

manager/build/cpodmanager-rbac.yaml
manager/cmd/cpodmanager/startcpodmanager.yaml
manager/pkg/communication/marketmanager.go
manager/pkg/job/job.go
manager/pkg/job/kubeflow-mpijob/mpijob.go
manager/pkg/log/log.go
manager/pkg/resource/resource.go

Fix cpodmanager issues

---

experimental/ceph-csi/deployment.yaml
experimental/ceph-csi/pvc.yaml
experimental/ceph-csi/sc.yaml
experimental/ceph-csi/secret.yaml
experimental/ceph-csi/statefulset.yaml

add_cephcsi_example

---

examples/bert/k8s_config/mpi_bert_ds_for_cephcsi.yaml

add mpi_bert_ds_for_cephcsi.yaml

---

examples/llama2/README.md

Add env vars for launching distributed pytorch training in README.md

---

examples/llama2/llama2_demo.py

Add logging to llama2_demo.py

---

manager/cmd/cpodmanager/startcpodmanager.yaml
manager/cmd/modeluploader/mannualstart.yaml
manager/pkg/job/kubeflow-mpijob/mpijob.go
manager/pkg/model-uploader/k8s_job.go

mpijob storage from cephfs to cephcsi(PVC)

---

cli/3kctl.py
cli/conf/config.ini
cli/deploy/deploy.py
cli/deploy/kubernetes.py
cli/deploy/registry.py
cli/deploy/utils.py
examples/bert/k8s_config/mpi_bert_ds_for_cephcsi.yaml

Add cli tool

---

cli/3kctl.py
cli/deploy/deploy.py
cli/deploy/kubernetes.py

change_switches_to_subcommands

---

manager/pkg/cluster/kubectl/README.md
manager/pkg/cluster/kubectl/kubectl.go

Not used, and does not seem needed in the future either
If needed, we can revert this commit

Remove kubectl package

---

manager/pkg/job/job.go

Having TODO linking to issue makes it easier for people to see where in the code should the change be made

Add TODO for moving jobs outside of cpod namespace in job.go

---

examples/llama2/llama2_demo.py

Changes to the training script for working with mpirun
https://tricorder.feishu.cn/wiki/A4DcwyoMciebNSkH8BOcFWlxnUd
https://tricorder.feishu.cn/wiki/JjBbwAx2QiT3Y2kbxioc7WN7nQg
https://tricorder.feishu.cn/wiki/JjBbwAx2QiT3Y2kbxioc7WN7nQg
**https://tricorder.feishu.cn/wiki/ZjtwwbZ4kiYDdGk90Yecqj8Bn6g** (latest result as of 202310292341 Pacific Time)

Changes to the training script for working with mpirun

---

manager/cmd/cpodmanager/cpodmanager.go
manager/pkg/communication/marketmanager.go
manager/pkg/job/job_state.go
manager/pkg/job/state/state.go
manager/pkg/model-uploader/model_uploader.go

jobs sych with portal

---

manager/cmd/cpodmanager/cpodmanager.go
manager/cmd/cpodmanager/startcpodmanager.yaml
manager/pkg/cluster/client-go/clientgo.go
manager/pkg/communication/marketmanager.go
manager/pkg/job/job.go
manager/pkg/job/kubeflow-mpijob/mpijob.go

create pvc before creating mpijob

---

manager/cmd/cpodmanager/cpodmanager.go
manager/cmd/cpodmanager/startcpodmanager.yaml
manager/cmd/modeluploader/modeluploadjob.go
manager/pkg/cluster/client-go/clientgo.go
manager/pkg/communication/marketmanager.go
manager/pkg/config/const.go
manager/pkg/config/fromenv.go
manager/pkg/job/job.go
manager/pkg/job/job_state.go
manager/pkg/log/log.go
manager/pkg/model-uploader/k8s_job.go
manager/pkg/model-uploader/model_uploader.go
manager/pkg/storage/oss.go

1. Http to Https 
2. add a thread in cpodmanager to delete completed jobs and related resources
3. add a config pkg to manage all the configs in cpodmanager and modeluploader

delete complete jobs and related pvc

---

devops/docker/cpodmanager/Dockerfile

delete unused dockerfile

---

manager/cmd/cpodmanager/startcpodmanager-prod.yaml
manager/cmd/cpodmanager/startcpodmanager-test.yaml
manager/cmd/modeluploader/mannualstart.yaml
manager/pkg/cluster/client-go/clientgo.go
manager/pkg/config/const.go
manager/pkg/config/fromenv.go
manager/pkg/model-uploader/k8s_job.go

1. 整理配置，不同的部署环境使用不同的配置
2. 修改Delete Job时的DeleteOption。

config for different deploy env

---

examples/llama2/Dockerfile
examples/llama2/k8s/llama2_deepspeed_mpi.yaml

YAML config for training LLaMA 2 on K8s.

Llama2 training on k8s

---

manager/pkg/job/kubeflow-mpijob/mpijob.go

modify kubeflow mpijob template for gang schedule

modify kubeflow mpijob template for gang schedule

---

cli/3kctl.py
cli/conf/config.ini
cli/deploy/deploy.py
cli/deploy/kubernetes.py
cli/deploy/utils.py

add init cpod info
add init apt source
add coredns reschedule
compatible ssh password/privatekey auth
fix node add ceph label bug

add init cpod info

---

manager/pkg/communication/marketmanager.go
manager/pkg/job/job.go
manager/pkg/job/kubeflow-mpijob/mpijob.go

use the portal input for pvc creation 

---

manager/pkg/communication/marketmanager.go
manager/pkg/config/const.go
manager/pkg/job/job.go
manager/pkg/job/kubeflow-mpijob/mpijob.go
manager/pkg/job/kubeflow-mpijob/mpijob_state.go

delete job when time up

---

manager/cmd/cpodmanager/cpodmanager.go
manager/cmd/cpodmanager/startcpodmanager-prod.yaml
manager/cmd/cpodmanager/startcpodmanager-test.yaml
manager/pkg/communication/marketmanager.go
manager/pkg/config/fromenv.go

 add access_key when communicate with portal

---

manager/cmd/cpodmanager/cpodmanager.go
manager/pkg/job/job.go
manager/pkg/job/kubeflow-mpijob/mpijob.go
manager/pkg/model-uploader/model_uploader.go

delete jobs when time up

---

manager/cmd/modeluploader/modeluploadjob.go
manager/pkg/config/const.go
manager/pkg/config/fromenv.go
manager/pkg/model-uploader/k8s_job.go
manager/pkg/model-uploader/model_uploader.go
manager/pkg/model-uploader/model_uploader_test.go
manager/pkg/storage/oss.go

get oss presigned url and post to market api

---

manager/pkg/job/kubeflow-mpijob/mpijob.go

remove dataset mount , remove command

---

manager/pkg/config/const.go
manager/pkg/model-uploader/model_uploader.go

exit normally when no presigned url file is found

change oss endpoint to https

---

aiadmin-web/src/api/system/fileurl.js
aiadmin-web/src/views/ai/info/index.vue
aiadmin/aiadmin-system/src/main/java/nascentcore/ai/modules/system/domain/Fileurl.java
aiadmin/aiadmin-system/src/main/java/nascentcore/ai/modules/system/domain/dto/file/ModelUrl.java
aiadmin/aiadmin-system/src/main/java/nascentcore/ai/modules/system/domain/vo/FileurlQueryCriteria.java
aiadmin/aiadmin-system/src/main/java/nascentcore/ai/modules/system/mapper/FileurlMapper.java
aiadmin/aiadmin-system/src/main/java/nascentcore/ai/modules/system/rest/InfoUploadController.java
aiadmin/aiadmin-system/src/main/java/nascentcore/ai/modules/system/rest/UserJobController.java
aiadmin/aiadmin-system/src/main/java/nascentcore/ai/modules/system/service/FileurlService.java
aiadmin/aiadmin-system/src/main/java/nascentcore/ai/modules/system/service/impl/FileurlServiceImpl.java
aiadmin/aiadmin-system/src/main/resources/mapper/system/FileurlMapper.xml

云市场实现将cpod上传的job的模型数据url展示出来及能够点击下载

---

cli/deploy/deploy.py
cli/deploy/kubernetes.py

change tenantid to accesskey

---

aiadmin-web/src/components/language/en.js
aiadmin-web/src/components/language/zh.js
aiadmin-web/src/views/ai/tool/guide.vue

增加算力源用户指南页

---

aiadmin-web/src/components/language/en.js
aiadmin-web/src/components/language/zh.js
aiadmin-web/src/views/ai/tool/userguide.vue

增加算力用户使用说明项，方便用户快速上手

---

manager/cmd/cpodmanager/startcpodmanager-prod.yaml
manager/cmd/cpodmanager/startcpodmanager-test.yaml
manager/pkg/cluster/client-go/clientgo.go
manager/pkg/job/job.go
manager/pkg/job/kubeflow-mpijob/mpijob_state.go

1. check pvc existence before create
2. deal with condition when status is not there

check pvc existence before create

---

aiadmin-web/src/components/language/en.js
aiadmin-web/src/components/language/zh.js
aiadmin-web/src/views/login.vue

增加客服电话和邮箱地址

---

home/donggang/README.md
home/donggang/bubble_sort.go
home/donggang/bubble_sort_test.go

donggang's first pr

---

aiadmin/aiadmin-system/src/main/java/nascentcore/ai/modules/security/security/TokenFilter.java
aiadmin/aiadmin-system/src/main/java/nascentcore/ai/modules/security/service/OnlineUserService.java

解决token失效问题

---

devops/gcp/add_data_disk.md

add gcp data disk

---

pkg/job/kubeflow-mpijob/mpijob_state.go
pkg/job/state/state.go

解决在任务参数异常时任务定时失效的问题

---

examples/env_verify/README.md
examples/env_verify/hello_modelscope_inference.py
examples/env_verify/hello_modelscope_train_multi.py
examples/env_verify/hello_modelscope_train_single.py
examples/env_verify/test_cuda.cmd
examples/env_verify/test_cudnn.cmd

检测以下项目
cuda
cuDNN
ModelScope的 推理、单机单卡训练、单机多卡训练

检测机器环境是否可以运行ModelScope

---

examples/gpt3/Dockerfile
examples/gpt3/README.md
examples/gpt3/configuration.json
examples/gpt3/ptjob_gpt3_1.3b_2h16g.yaml

完善多机多卡测试任务
增加gpt3-1.3B finetuning 多机训练任务

feat: add gpt1.3 multnode train example

---

cmd/cpodmanager/datasetstoragecrd.yaml
cmd/cpodmanager/datasetstoragesample.yaml
cmd/cpodmanager/modelstoragecrd.yaml
cmd/cpodmanager/modelstoragesample.yaml
pkg/communication/marketmanager.go
pkg/config/const.go
pkg/job/job.go
pkg/job/kubeflow-mpijob/mpijob.go
pkg/job/kubeflow-pytorchjob/README.md
pkg/job/kubeflow-pytorchjob/pytorchjob.go
pkg/job/kubeflow-pytorchjob/pytorchjob_state.go
pkg/job/modelstorage.go
pkg/job/utils/README.md
pkg/job/utils/datasetstorage.go
pkg/job/utils/modelstorage.go
pkg/job/utils/utils.go
pkg/job/utils/utils_test.go
pkg/model-uploader/model_uploader.go

add pytorch job , add modelstorage and datasetstorage crd

---

pkg/cluster/client-go/clientgo.go
pkg/communication/marketmanager.go
pkg/config/const.go
pkg/job/general-job/README.md
pkg/job/general-job/generaljob.go
pkg/job/general-job/generaljob_state.go
pkg/job/job.go
pkg/job/kubeflow-mpijob/mpijob.go
pkg/job/kubeflow-pytorchjob/pytorchjob.go
pkg/job/utils/podtemplate.go
pkg/model-uploader/k8s_job.go

add generaljob ; more information from portal ; optimize code

---

aiadmin/aiadmin-system/src/main/java/nascentcore/ai/modules/system/rest/UserJobController.java
aiadmin/aiadmin-system/src/main/java/nascentcore/ai/modules/system/service/JobManager.java
aiadmin/aiadmin-system/src/main/java/nascentcore/ai/modules/system/thread/HttpSenddateThread.java

modify sucess to success

---

aiadmin/aiadmin-common/src/main/java/nascentcore/ai/utils/DateUtil.java
aiadmin/aiadmin-system/src/main/java/nascentcore/ai/modules/system/domain/UserJob.java
aiadmin/aiadmin-system/src/main/java/nascentcore/ai/modules/system/domain/UserJobRes.java
aiadmin/aiadmin-system/src/main/java/nascentcore/ai/modules/system/domain/dto/job/EnvDTO.java
aiadmin/aiadmin-system/src/main/java/nascentcore/ai/modules/system/rest/InfoUploadController.java
aiadmin/aiadmin-system/src/main/java/nascentcore/ai/modules/system/rest/UserJobController.java
aiadmin/aiadmin-system/src/main/java/nascentcore/ai/modules/system/service/JobManager.java
aiadmin/aiadmin-system/src/main/resources/mapper/system/UserJobMapper.xml

增加evn参数同时修改job的创建时间为北京时间

---

cmd/cpodmanager/buildimage.sh
cmd/cpodmanager/cpodmanager.go
cmd/modeluploader/buildimage.sh
pkg/communication/marketmanager.go
pkg/job/general-job/generaljob.go
pkg/job/general-job/generaljob_state.go
pkg/job/job.go
pkg/job/job_state.go
pkg/job/kubeflow-mpijob/mpijob.go
pkg/job/kubeflow-pytorchjob/pytorchjob.go
pkg/job/utils/podtemplate.go

fix upload status

---

aiadmin/aiadmin-system/src/main/java/nascentcore/ai/modules/system/domain/dto/job/EnvDTO.java

修改MODIHAND_OPEN_NODE_TOKEN会自动转成小写问题

---

devops/ansible/README.md
devops/ansible/user.yaml

add user playbook

---

examples/bert/train_bert_ds.py

change-train-bert-ds

---

3kctl/deploy/deploy.py
3kctl/deploy/kubernetes.py
3kctl/requirements.txt
deployment/values/ceph-csi-cephfs.yaml

add ceph-csi-cephfs deploy

---

pkg/job/kubeflow-mpijob/mpijob.go

add ExecutionDurationSeconds

---

examples/gpt3/gpt3_pvc.yaml
examples/gpt3/ptjob_gpt3_1.3b_1h1g.yaml
examples/gpt3/ptjob_gpt3_1.3b_1h8g.yaml
examples/gpt3/ptjob_gpt3_1.3b_2h16g.yaml

update gpt3 mount pvc

---

3kctl/download/download.py
3kctl/download/hugging_face.py

3kctl support hugging_face

---

cmd/cpodmanager/cpodmanager.go
pkg/job/kubeflow-mpijob/mpijob.go
pkg/portal-sync/portal_sync.go

用户提交的任务如果参数有错误在创建Job时报错，向Portal上报CreateFailed状态。

add createfailed status upload

---

aiadmin/aiadmin-common/src/main/java/nascentcore/ai/config/SystemConfig.java
aiadmin/aiadmin-common/src/main/java/nascentcore/ai/utils/EncryptUtils.java
aiadmin/aiadmin-common/src/main/java/nascentcore/ai/utils/StringUtils.java
aiadmin/aiadmin-system/src/main/java/nascentcore/ai/modules/system/domain/Config.java
aiadmin/aiadmin-system/src/main/java/nascentcore/ai/modules/system/domain/vo/ConfigQueryCriteria.java
aiadmin/aiadmin-system/src/main/java/nascentcore/ai/modules/system/mapper/ConfigMapper.java
aiadmin/aiadmin-system/src/main/java/nascentcore/ai/modules/system/service/ConfigService.java
aiadmin/aiadmin-system/src/main/java/nascentcore/ai/modules/system/service/impl/ConfigServiceImpl.java
aiadmin/aiadmin-system/src/main/java/nascentcore/ai/modules/system/task/AiadminTaskStartupRunner.java
aiadmin/aiadmin-system/src/main/java/nascentcore/ai/modules/system/thread/HttpSenddateThread.java
aiadmin/aiadmin-system/src/main/resources/mapper/system/ConfigMapper.xml

加密的密钥在代码中写死的
实现密钥不在开源代码中出现，放于后端的数据库中
无

将加密的密钥key移出代码外，放于数据库中管理存储

---

cmd/cpodmanager/cpodmanager.go
pkg/job/job.go
pkg/job/state/state.go
pkg/resource/resource.go

add model / dataset cache in upload info

---

aiadmin-web/package.json
aiadmin-web/src/api/system/fileurl.js
aiadmin-web/src/components/language/en.js
aiadmin-web/src/components/language/zh.js
aiadmin-web/src/views/ai/info/index.vue
aiadmin-web/src/views/ai/order/index.vue
aiadmin/aiadmin-system/src/main/java/nascentcore/ai/modules/system/domain/AliPayRes.java
aiadmin/aiadmin-system/src/main/java/nascentcore/ai/modules/system/domain/Order.java
aiadmin/aiadmin-system/src/main/java/nascentcore/ai/modules/system/domain/vo/OrderQueryCriteria.java
aiadmin/aiadmin-system/src/main/java/nascentcore/ai/modules/system/mapper/OrderMapper.java
aiadmin/aiadmin-system/src/main/java/nascentcore/ai/modules/system/rest/OrderController.java
aiadmin/aiadmin-system/src/main/java/nascentcore/ai/modules/system/service/OrderService.java
aiadmin/aiadmin-system/src/main/java/nascentcore/ai/modules/system/service/impl/OrderServiceImpl.java
aiadmin/aiadmin-system/src/main/resources/mapper/system/OrderMapper.xml
aiadmin/aiadmin-tools/pom.xml
aiadmin/aiadmin-tools/src/main/java/nascentcore/ai/domain/AlipayConfig.java
aiadmin/aiadmin-tools/src/main/java/nascentcore/ai/domain/vo/TradeVo.java
aiadmin/aiadmin-tools/src/main/java/nascentcore/ai/mapper/AliPayConfigMapper.java
aiadmin/aiadmin-tools/src/main/java/nascentcore/ai/rest/AliPayController.java
aiadmin/aiadmin-tools/src/main/java/nascentcore/ai/service/AliPayService.java
aiadmin/aiadmin-tools/src/main/java/nascentcore/ai/service/impl/AliPayServiceImpl.java
aiadmin/aiadmin-tools/src/main/java/nascentcore/ai/utils/AliPayStatusEnum.java
aiadmin/aiadmin-tools/src/main/java/nascentcore/ai/utils/AlipayUtils.java

增加阿里支付相关功能

---

aiadmin/aiadmin-system/src/main/java/nascentcore/ai/modules/system/rest/InfoUploadController.java
aiadmin/aiadmin-system/src/main/java/nascentcore/ai/modules/system/service/JobManager.java

之前返回模型上传ok状态早于，url接口调用，把发回调消息放在了url接口调用中，后来三千解决了早报状态问题，从而发消息回调需要跟着调整到报状态后
实现回调成功
无

解决无法触发回调函数问题

---

3kctl/README.md
3kctl/download/download.py
3kctl/download/k8s.py
cmd/downloader/Dockerfile
cmd/downloader/cmd/git.go
cmd/downloader/internal/download/download.go
cmd/downloader/internal/record/record.go

hugging face需要vpn才能访问
add vpn support for downloader
无

add vpn support for downloader

---

go.sum
gomicro/go-zero-template/api/handler.tpl
gomicro/go-zero-template/model/model.tpl
gomicro/pkg/consts/job.go
gomicro/pkg/sxwlzero/rest.go
gomicro/scheduler/Dockerfile
gomicro/scheduler/README.md
gomicro/scheduler/client.api
gomicro/scheduler/etc/scheduler-api.yaml
gomicro/scheduler/etc/scheduler-api_prod.yaml
gomicro/scheduler/etc/scheduler-api_test.yaml
gomicro/scheduler/internal/config/config.go
gomicro/scheduler/internal/handler/cpod_status_handler.go
gomicro/scheduler/internal/logic/cpod_status_logic.go
gomicro/scheduler/internal/model/sys_cpod_main_model.go
gomicro/scheduler/internal/model/sys_cpod_main_model_gen.go
gomicro/scheduler/internal/model/sys_fileurl_model.go
gomicro/scheduler/internal/model/sys_user_job_model.go
gomicro/scheduler/internal/model/sys_user_job_model_gen.go
gomicro/scheduler/internal/svc/service_context.go
gomicro/scheduler/internal/types/types.go
gomicro/scheduler/scheduler.api
gomicro/scheduler/scheduler.go

scheduler cpod_status api

---

pkg/communication/validate.go
pkg/communication/validate_test.go

add validate function

---

pkg/job/general-job/generaljob.go
pkg/job/kubeflow-mpijob/mpijob.go
pkg/job/kubeflow-pytorchjob/pytorchjob.go
pkg/job/utils/podtemplate.go

add container name for pytorchjob

---

aiadmin/aiadmin-common/src/main/java/nascentcore/ai/config/ServiceProperties.java
aiadmin/aiadmin-system/src/main/java/nascentcore/ai/modules/system/rest/InfoUploadController.java
aiadmin/aiadmin-system/src/main/java/nascentcore/ai/modules/system/rest/UserJobController.java
aiadmin/aiadmin-system/src/main/resources/config/application-dev.yml
aiadmin/aiadmin-system/src/main/resources/config/application-prod.yml

java为支撑go-scheduler 模块分离的cpod_status和upload_status两个接口的透传处理

---

aiadmin/aiadmin-system/src/main/java/nascentcore/ai/modules/security/rest/AuthorizationController.java
aiadmin/aiadmin-system/src/main/java/nascentcore/ai/modules/system/service/VerifyService.java
aiadmin/aiadmin-system/src/main/java/nascentcore/ai/modules/system/service/impl/VerifyServiceImpl.java
aiadmin/aiadmin-system/src/main/resources/template/token.ftl

新注册用户为其发送accesskey邮件，方便后续有使用api调用服务用户

---

.github/workflows/sxcloud-java-build.yaml
deployment/sxcloud/Dockerfile

无
增加算想云java部分的github action的CI功能
无

增加算想云java部分的github action的CI

---

cmd/modeluploader/modeluploadjob.go

modeluploader  without wait

---

gomicro/gateway/internal/gateway/handler.go

修复/auth接口鉴权逻辑 build:v0.0.5

---

ty/README.md
ty/bubble_sort.go

> None
> Bubble Sort using goalong

First pr on bubble sort

---

home/zhongcheng/README.md
home/zhongcheng/bubble_sort.go
home/zhongcheng/bubble_sort_test.go

> 配置
>  第一个PR ，完成本地的ssh key和配置

zhc's first pr

---

.github/workflows/go.yml
.gitignore
README.md

> 增加go语言的test的输出，对接codecov
> 对接codecov，并在readme里面显示

Add codecov

---

cmd/modeluploader/buildimage.sh
pkg/model-uploader/model_uploader.go

Modeluploader

---

e2e/b_mpijob_test.go
e2e/b_pytorchjob_test.go
e2e/c_gpt3_test.go
e2e/ib/ib.yaml
e2e/main_test.go
e2e/mpijob/mnist.yaml
e2e/pytorchjob/multinode.yaml

fix: fix e2e bug

---

examples/llama2/finetuning-and-deploy/README.md
examples/llama2/finetuning-and-deploy/cpodjob.yaml
examples/llama2/finetuning-and-deploy/inferenceservice.yaml

feat: add llama-2-7b finetuning and inference deploy case

---

gomicro/scheduler/internal/handler/resource_handler.go
gomicro/scheduler/internal/handler/routes.go
gomicro/scheduler/internal/logic/cpod_status_logic.go
gomicro/scheduler/internal/logic/resource_logic.go
gomicro/scheduler/internal/model/sys_cpod_cache_model.go
gomicro/scheduler/scheduler.api

https://github.com/NascentCore/3k/issues/462

增加查询模型的接口 build:v0.0.24

---

gomicro/gateway/etc/gateway-api.yaml
gomicro/gateway/etc/gateway-api_prod.yaml
gomicro/gateway/etc/gateway-api_test.yaml

https://github.com/NascentCore/3k/issues/462

增加查询模型和数据集的接口 build:v0.0.10

---

examples/docker/README.md
examples/docker/torch_base.Dockerfile

add torch base dockerfile

---

examples/llama2/finetuning-and-deploy/Dockerfile
examples/llama2/finetuning-and-deploy/README.md
examples/llama2/finetuning-and-deploy/inferenceservice.yaml

feat: improve llama-2-7b finetuning and inference case

---

aiadmin/aiadmin-system/src/main/java/nascentcore/ai/modules/system/domain/vo/CpodMainQueryCriteria.java
aiadmin/aiadmin-system/src/main/java/nascentcore/ai/modules/system/domain/vo/FileurlQueryCriteria.java
aiadmin/aiadmin-system/src/main/java/nascentcore/ai/modules/system/domain/vo/OrderQueryCriteria.java
aiadmin/aiadmin-system/src/main/java/nascentcore/ai/modules/system/domain/vo/PriceQueryCriteria.java
aiadmin/aiadmin-system/src/main/java/nascentcore/ai/modules/system/domain/vo/UserJobQueryCriteria.java
aiadmin/aiadmin-system/src/main/java/nascentcore/ai/modules/system/domain/vo/UserQueryCriteria.java
aiadmin/aiadmin-system/src/main/java/nascentcore/ai/modules/system/rest/InfoUploadController.java
aiadmin/aiadmin-system/src/main/java/nascentcore/ai/modules/system/rest/UserJobController.java
aiadmin/aiadmin-tools/src/main/java/nascentcore/ai/rest/AliPayController.java
aiadmin/aiadmin-tools/src/main/java/nascentcore/ai/rest/EmailController.java

在swagger接口展示页面里增加swagger入参注解，删除多余没用到的函数接口，将已移植到go语言模块的函数添加 已挪go标签文字

---

go.mod
go.sum
pkg/utils/config/configmap.go
pkg/utils/config/configmap_test.go

add get configmap values

---

.github/workflows/python.yaml
3kctl/deploy/test_utils.py

add python unittest

---

examples/llama2-full-param-finetune/Dockerfile

add llama2-7b finetune Dockerfile

---

deployment/models/pre_loaded.txt

add https://huggingface.co/stabilityai/stable-code-3b

add preloaded model

---

3kctl/download/download.py
3kctl/download/model_scope.py

https://github.com/NascentCore/3k/issues/512

修复下载器申请pvc过小问题

---

home/congpeiqing/code-retreat/code_retreat.go
home/congpeiqing/code-retreat/code_retreat_test.go
home/congpeiqing/code-retreat/main.go

code-retreat  tdd

---

home/cairong/game-of-live/main.go
home/cairong/game-of-live/main_test.go

Code retreat Cairong

---

examples/llamafactory/Dockerfile
examples/llamafactory/README.md
examples/llamafactory/dataset_info.json

feat: add chatglm3-6b fine tuning by llama factory example

---

3kctl/conf/config.ini
3kctl/conf/softwares.yaml
3kctl/deploy/deploy.py
3kctl/deploy/kubernetes.py
3kctl/deploy/software.py
3kctl/deploy/test_software.py
3kctl/deploy/test_utils.py
3kctl/deploy/utils.py

Optimize software installation logic

---

cpodoperator/internal/synchronizer/syncjob.go

prepare for create inference jobs

---

cpodoperator/cmd/portalsynch/main.go
cpodoperator/config/manager/portalsynch.yaml

change rbac and url

---

cpodoperator/internal/synchronizer/cpodobserver.go

add inferenceservice to payload

---

.github/workflows/preload-model.yaml
deployment/models/pre_loaded.txt

add preload model workflow

---

deployment/manifest/make-package.sh
deployment/manifest/manifest.yaml

add make offline package pipeline

---

cpodoperator/internal/synchronizer/syncjob.go

portal inference job to  cpod inference job 

---

cpodoperator/cmd/operator/main.go
cpodoperator/config/crd/bases/cpod_datasetstorages.yaml
cpodoperator/config/crd/bases/cpod_modelstorages.yaml
cpodoperator/internal/controller/inference_controller.go

feat: create ingress of inferenc

---

rag/README.md
rag/rag-service-deployment.yaml
rag/rag-service-service.yaml
rag/service.py

fix rag run error

---

3kctl/conf/softwares.yaml
deployment/manifest/manifest.yaml
deployment/yaml_apps/dashboard-admin-sa.yaml
deployment/yaml_apps/kubernetes-dashboard.yaml

add kubernetes dashboard

---

cpodoperator/cmd/operator/main.go
cpodoperator/internal/controller/inference_controller.go

update the ingress generate rule of inference

---

3kctl/conf/softwares.yaml
deployment/jupyterlab/Dockerfile
deployment/manifest/manifest.yaml
deployment/yaml_apps/jupyterlab.yaml

add tensorboard and jupyterlab deployment

---

cpodoperator/cmd/portalsynch/main.go
cpodoperator/config/manager/portalsynch.yaml
cpodoperator/internal/synchronizer/cpodobserver.go
cpodoperator/internal/synchronizer/manager.go
cpodoperator/internal/synchronizer/syncjob.go
cpodoperator/pkg/provider/sxwl/interface.go

download model and dataset when not present

download model and dataset when not present

---

cpodoperator/go.mod
cpodoperator/internal/controller/cpodjob_controller.go
cpodoperator/internal/controller/cpodjob_controller_test.go

cpodjob 创建时自动挂载 logs pvc 到 /logs 目录，任务启动时指定相应参数 --report_to=tensorboard --logging_dir=/logs 即可将日志写入并在 tensordboard 上展示

add logs pvc for cpodjob

---

examples/p-eval/eval.py

add performance eval

---

cpodoperator/internal/synchronizer/cpodobserver.go
internal/scheduler/logic/cpod_status_logic.go

fix finetune sync build:v0.0.74

---

ui/config/routes.ts
ui/src/locales/en-US.ts
ui/src/locales/en-US/modelRepository.ts
ui/src/locales/en-US/userJobCommit.ts
ui/src/locales/zh-CN.ts
ui/src/locales/zh-CN/modelRepository.ts
ui/src/locales/zh-CN/userJob.ts
ui/src/locales/zh-CN/userJobCommit.ts
ui/src/pages/ModelRepository/FineTuningDrawer/index.tsx
ui/src/pages/ModelRepository/InferenceDrawer/index.tsx
ui/src/pages/UserJobCommit/index.tsx
ui/src/services/index.ts

修改微调&部署提交参数&任务提交页面迁移

---

ui/config/routes.ts
ui/src/locales/en-US.ts
ui/src/locales/en-US/clusterInformation.ts
ui/src/locales/en-US/userQuota.ts
ui/src/locales/zh-CN.ts
ui/src/locales/zh-CN/clusterInformation.ts
ui/src/locales/zh-CN/userQuota.ts
ui/src/pages/ClusterInformation/AddNodeDrawer/index.tsx
ui/src/pages/ClusterInformation/index.tsx
ui/src/pages/UserQuota/EditDrawer/index.tsx
ui/src/pages/UserQuota/index.tsx
ui/src/services/index.ts

feat: webui 新增集群信息和用户配额菜单

---

home/steven/README.md

create readme.md file
create bubble_sort.go and bubble_sort_test.go

steven's first_pr

---

home/wenhua/README.md

added README.md
completed bubble_sort.go and bubble_sort_test.go

wenhua's first pr

---

ui/src/pages/InferenceState/index.tsx

fix: webui 推理服务，隐藏url字段

---

ui/src/app.tsx

feat: webui 添加文档和价格链接

---

ui/src/locales/en-US/global.ts
ui/src/locales/en-US/modelRepository.ts
ui/src/locales/zh-CN/global.ts
ui/src/locales/zh-CN/modelRepository.ts
ui/src/pages/ModelRepository/FineTuningDrawer/index.tsx
ui/src/pages/UserJobCommit/index.tsx
ui/src/pages/UserQuota/EditDrawer/index.tsx
ui/src/services/index.ts

feat: 修改微调参数

---

ui/src/locales/en-US/modelRepository.ts
ui/src/locales/zh-CN/modelRepository.ts
ui/src/pages/ModelRepository/InferenceDrawer/index.tsx

feat: webui 推理参数修改

---

ui/src/pages/User/Login/LoginForm/index.tsx

feat: 新增登录邮箱验证码

---

ui/src/locales/en-US/login.ts
ui/src/locales/zh-CN/login.ts
ui/src/pages/User/Login/LoginForm/index.tsx

feat: 修改webui 登录方式

---

ui/src/pages/ModelRepository/index.tsx

feat: webui 修改模型仓库列表

---

ui/src/components/RightContent/AvatarDropdown.tsx
ui/src/locales/en-US/global.ts
ui/src/locales/zh-CN/global.ts
ui/src/pages/Adapter/index.tsx
ui/src/pages/Dataset/index.tsx
ui/src/pages/ModelRepository/index.tsx

feat: WebUI 修改模型仓库，数据集，适配器页面

---

ui/src/locales/en-US/modelRepository.ts
ui/src/locales/zh-CN/modelRepository.ts
ui/src/pages/InferenceState/index.tsx
ui/src/pages/ModelRepository/InferenceDrawer/index.tsx
ui/src/pages/ModelRepository/index.tsx

feat: 修改webui

---

ui/config/routes.ts
ui/src/locales/en-US.ts
ui/src/locales/en-US/applicationMenu.ts
ui/src/locales/en-US/global.ts
ui/src/locales/zh-CN.ts
ui/src/locales/zh-CN/applicationMenu.ts
ui/src/locales/zh-CN/global.ts
ui/src/pages/ApplicationManagement/AddAppForm/index.tsx
ui/src/pages/ApplicationManagement/index.tsx
ui/src/pages/ApplicationMenu/AddAppForm/index.tsx
ui/src/pages/ApplicationMenu/AppCard/index.tsx
ui/src/pages/ApplicationMenu/index.tsx
ui/src/services/index.ts

feat: WebUI 新增大模型应用页面

---

ui/pkg/sumdb/sum.golang.org/latest
ui/src/locales/en-US/applicationMenu.ts
ui/src/locales/en-US/inferenceState.ts
ui/src/locales/zh-CN/applicationMenu.ts
ui/src/locales/zh-CN/inferenceState.ts
ui/src/pages/ApplicationMenu/AddAppForm/index.tsx
ui/src/pages/InferenceState/index.tsx

1. add llm integrated for rag app
2. add copy api endpoint for inference instance
3. add locales config

add llm integrated for rag app

---

examples/rag-h5/script.js

fix: rag-h5 添加容错
